version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
       - db_data: /var/lib/mysql
    restart: always
    enviroment:
      MYSQL_ROOT_PASSWORD: superpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpress

  wordpress:
      depends-on:
        -db
      image: wordpress:latest
      ports:
        -"8080:80"
      restart: always
      enviroment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpressuser
        WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:


